apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo
  labels:
    app: mongo-database
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mongo-database
  template:
    metadata:
      labels:
        app: mongo-database
    spec:
      containers:
        - name: mongo-database
          image: mongo:5.0
          ports:
            - containerPort: 27017
          env:
            - name: MONGO_DB_USER
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: mongo-user
            - name: MONGO_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: mongo-password
          resources:
            limits:
              cpu: '1'
              memory: '1Gi'
            requests:
              cpu: '0.5'
              memory: '512Mi'

---
apiVersion: v1
kind: Service
metadata:
  name: mongo-service
spec:
  selector:
    app: mongo-database
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
